---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: local
    hooks:
      - id: ty-type-check
        name: ty type checker
        entry: uv run ty check
        language: system
        pass_filenames: false
        types: [python]
